[package]
name = "frontend"
version = "0.1.0"
authors = ["Callum Jacob Hays <callumjhays@gmail.com>"]
edition = "2018"

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", features = ["cbor"] }