[package]
name = "backend"
version = "0.0.0"
authors = ["Callum Hays <callumjhays@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
sentry = "0.12.0"
sentry-actix = "0.12.0"
listenfd = "0.3"

[dev-dependencies]
systemfd = "0.3"
cargo-watch = "7.0"